# Generated by Django 5.0.4 on 2024-04-20 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_trainer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название плана питания')),
                ('description', models.TextField(verbose_name='Описание плана питания')),
                ('start_date', models.DateField(verbose_name='Дата начала выполнения')),
                ('end_date', models.DateField(verbose_name='Дата окончания выполнения')),
            ],
            options={
                'verbose_name': 'План питания',
                'verbose_name_plural': 'План питания',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название упражнения')),
                ('description', models.TextField(verbose_name='Описание упражнения')),
                ('muscle_group', models.CharField(max_length=100, verbose_name='Группа мышц')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тренировки')),
                ('description', models.TextField(verbose_name='Описание тренировки')),
                ('duration', models.DurationField(verbose_name='Продолжительность тренировки')),
                ('exercise', models.ManyToManyField(to='workouts.exercise', verbose_name='Упражнения')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trainer')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название плана тренировок')),
                ('description', models.TextField(verbose_name='Описание плана тренировок')),
                ('start_date', models.DateField(verbose_name='Дата начала выполнения')),
                ('end_date', models.DateField(verbose_name='Дата окончания выполнения')),
                ('workouts', models.ManyToManyField(to='workouts.workout', verbose_name='Тренировки в плане')),
            ],
            options={
                'verbose_name': 'План тренировки',
                'verbose_name_plural': 'План тренировок',
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField(verbose_name='Дата выполнения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Журнал тренировки',
                'verbose_name_plural': 'Журнал тренировок',
            },
        ),
    ]
